# Generated by Django 2.0.6 on 2018-07-01 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='note',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
