# Generated by Django 2.0.6 on 2018-07-01 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20180701_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='create_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
